config/routes.rb
Rails.application.routes.draw do
  resources :games do
    collection do
      post :set_platform_filter
    end

    collection do
      post :set_publisher_filter
    end
  end

  get 'archive/index'
  get 'archive/checkout'
  get 'archive/search'
  get 'archive/collections'
  get 'archive/wishlist'

  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root "games#index"

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/views/layouts/_navbar.html.erb
<div class=" flex justify-between bg-indigo-500 shadow-xl text-white""> 

  <div class="flex pt-4">
    <h1 class="text-2xl font-bold pl-4 pr-8 shadow-xl"> <%= link_to 'The Archive', root_path %></h1>
    <button type="button" class="hover:underline hover:font-bold"><%= link_to 'Collection', root_path %></button>
    <text class="px-2">|</text>
    <button type="button" class="hover:underline hover:font-bold"><%= link_to 'Checkout', archive_checkout_path %> </button>
    <text class="px-2">|</text>
    <button type="button" class="hover:underline hover:font-bold"><%= link_to 'Wishlist', archive_wishlist_path %></button>
  </div>



  <div class="flex mx-8 pt-4"> 
    <div class="flex"> 
      <button type="button" class="mr-4 hover:underline hover:font-bold"><%= link_to 'Archive', archive_search_path %></button>
      <button type="button" class="hover:underline hover:font-bold"><%= link_to 'Explore', archive_collections_path %></button>
    </div>
    <text class="mx-8">|</text>
  <button type="button" class="mr-4 hover:underline hover:font-bold"><%= link_to 'Account', edit_user_registration_path %></button>
  <button type="button" class="hover:underline hover:font-bold"><%= link_to "Log out", destroy_user_session_path %></button>
  </div>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Archive Tracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <% if user_signed_in? %>
      <%= render "layouts/navbar" %>
    <% end %>      
    <main class="">
      <%= yield %>
    </main>

  </body>
</html>